/*
   Generated by EX4-TO-MQ4 decompiler V4.0.224.1 []
   Website: http://purebeam.biz
   E-mail : purebeam@gmail.com
*/
#property copyright "Copyright © 2007."
#property link      "http://www.ekosignal.com"

#property indicator_chart_window

int gi_unused_76 = 7;
extern bool Corner_of_Chart_RIGHT_TOP = TRUE;
extern bool Show_Price = TRUE;
extern bool Show_Xtra_Details = TRUE;
extern bool Show_Smaller_Size = TRUE;
int gi_100 = 0;
int gi_104 = 20;
int g_color_108 = LightSteelBlue;
int g_color_112 = LightSteelBlue;
int g_period_116 = 12;
int g_period_120 = 26;
int g_period_124 = 9;
int g_applied_price_128 = PRICE_CLOSE;
int g_period_132 = 14;
int g_applied_price_136 = PRICE_CLOSE;
int g_period_140 = 13;
int g_applied_price_144 = PRICE_CLOSE;
int g_period_148 = 5;
int g_period_152 = 3;
int g_slowing_156 = 3;
int g_ma_method_160 = MODE_EMA;
int g_period_164 = 5;
int g_period_168 = 9;
int g_ma_method_172 = MODE_EMA;
int g_applied_price_176 = PRICE_CLOSE;

int init() {
   return (0);
}

int deinit() {
   ObjectsDeleteAll(0, OBJ_LABEL);
   return (0);
}

int start() {
   color l_color_0;
   color l_color_4;
   color l_color_8;
   color l_color_12;
   color l_color_16;
   color l_color_20;
   color l_color_24;
   color l_color_28;
   color l_color_32;
   color l_color_36;
   color l_color_40;
   color l_color_44;
   color l_color_48;
   color l_color_52;
   string ls_unused_56;
   color l_color_64;
   color l_color_68;
   int l_ind_counted_72 = IndicatorCounted();
   string l_text_76 = "";
   string l_text_84 = "";
   string l_text_92 = "";
   string l_text_100 = "";
   string l_text_108 = "";
   string l_text_116 = "";
   string l_text_124 = "";
   double l_imacd_132 = iMACD(NULL, PERIOD_M1, g_period_116, g_period_120, g_period_124, g_applied_price_128, MODE_MAIN, 0);
   double l_imacd_140 = iMACD(NULL, PERIOD_M1, g_period_116, g_period_120, g_period_124, g_applied_price_128, MODE_SIGNAL, 0);
   double l_imacd_148 = iMACD(NULL, PERIOD_M5, g_period_116, g_period_120, g_period_124, g_applied_price_128, MODE_MAIN, 0);
   double l_imacd_156 = iMACD(NULL, PERIOD_M5, g_period_116, g_period_120, g_period_124, g_applied_price_128, MODE_SIGNAL, 0);
   double l_imacd_164 = iMACD(NULL, PERIOD_M15, g_period_116, g_period_120, g_period_124, g_applied_price_128, MODE_MAIN, 0);
   double l_imacd_172 = iMACD(NULL, PERIOD_M15, g_period_116, g_period_120, g_period_124, g_applied_price_128, MODE_SIGNAL, 0);
   double l_imacd_180 = iMACD(NULL, PERIOD_M30, g_period_116, g_period_120, g_period_124, g_applied_price_128, MODE_MAIN, 0);
   double l_imacd_188 = iMACD(NULL, PERIOD_M30, g_period_116, g_period_120, g_period_124, g_applied_price_128, MODE_SIGNAL, 0);
   double l_imacd_196 = iMACD(NULL, PERIOD_H1, g_period_116, g_period_120, g_period_124, g_applied_price_128, MODE_MAIN, 0);
   double l_imacd_204 = iMACD(NULL, PERIOD_H1, g_period_116, g_period_120, g_period_124, g_applied_price_128, MODE_SIGNAL, 0);
   double l_imacd_212 = iMACD(NULL, PERIOD_H4, g_period_116, g_period_120, g_period_124, g_applied_price_128, MODE_MAIN, 0);
   double l_imacd_220 = iMACD(NULL, PERIOD_H4, g_period_116, g_period_120, g_period_124, g_applied_price_128, MODE_SIGNAL, 0);
   double l_imacd_228 = iMACD(NULL, PERIOD_D1, g_period_116, g_period_120, g_period_124, g_applied_price_128, MODE_MAIN, 0);
   double l_imacd_236 = iMACD(NULL, PERIOD_D1, g_period_116, g_period_120, g_period_124, g_applied_price_128, MODE_SIGNAL, 0);
   if (l_imacd_132 > l_imacd_140) {
      l_text_100 = "-";
      l_color_12 = Green;
   }
   if (l_imacd_132 <= l_imacd_140) {
      l_text_100 = "-";
      l_color_12 = Tomato;
   }
   if (l_imacd_132 > l_imacd_140 && l_imacd_132 > 0.0) {
      l_text_100 = "-";
      l_color_12 = Lime;
   }
   if (l_imacd_132 <= l_imacd_140 && l_imacd_132 < 0.0) {
      l_text_100 = "-";
      l_color_12 = Red;
   }
   if (l_imacd_148 > l_imacd_156) {
      l_text_108 = "-";
      l_color_16 = Green;
   }
   if (l_imacd_148 <= l_imacd_156) {
      l_text_108 = "-";
      l_color_16 = Tomato;
   }
   if (l_imacd_148 > l_imacd_156 && l_imacd_148 > 0.0) {
      l_text_108 = "-";
      l_color_16 = Lime;
   }
   if (l_imacd_148 <= l_imacd_156 && l_imacd_148 < 0.0) {
      l_text_108 = "-";
      l_color_16 = Red;
   }
   if (l_imacd_164 > l_imacd_172) {
      l_text_116 = "-";
      l_color_20 = Green;
   }
   if (l_imacd_164 <= l_imacd_172) {
      l_text_116 = "-";
      l_color_20 = Tomato;
   }
   if (l_imacd_164 > l_imacd_172 && l_imacd_164 > 0.0) {
      l_text_116 = "-";
      l_color_20 = Lime;
   }
   if (l_imacd_164 <= l_imacd_172 && l_imacd_164 < 0.0) {
      l_text_116 = "-";
      l_color_20 = Red;
   }
   if (l_imacd_180 > l_imacd_188) {
      l_text_124 = "-";
      l_color_24 = Green;
   }
   if (l_imacd_180 <= l_imacd_188) {
      l_text_124 = "-";
      l_color_24 = Tomato;
   }
   if (l_imacd_180 > l_imacd_188 && l_imacd_180 > 0.0) {
      l_text_124 = "-";
      l_color_24 = Lime;
   }
   if (l_imacd_180 <= l_imacd_188 && l_imacd_180 < 0.0) {
      l_text_124 = "-";
      l_color_24 = Red;
   }
   if (l_imacd_196 > l_imacd_204) {
      l_text_84 = "-";
      l_color_4 = Green;
   }
   if (l_imacd_196 <= l_imacd_204) {
      l_text_84 = "-";
      l_color_4 = Tomato;
   }
   if (l_imacd_196 > l_imacd_204 && l_imacd_196 > 0.0) {
      l_text_84 = "-";
      l_color_4 = Lime;
   }
   if (l_imacd_196 <= l_imacd_204 && l_imacd_196 < 0.0) {
      l_text_84 = "-";
      l_color_4 = Red;
   }
   if (l_imacd_212 > l_imacd_220) {
      l_text_92 = "-";
      l_color_8 = Green;
   }
   if (l_imacd_212 <= l_imacd_220) {
      l_text_92 = "-";
      l_color_8 = Tomato;
   }
   if (l_imacd_212 > l_imacd_220 && l_imacd_212 > 0.0) {
      l_text_92 = "-";
      l_color_8 = Lime;
   }
   if (l_imacd_212 <= l_imacd_220 && l_imacd_212 < 0.0) {
      l_text_92 = "-";
      l_color_8 = Red;
   }
   if (l_imacd_228 > l_imacd_236) {
      l_text_76 = "-";
      l_color_0 = Green;
   }
   if (l_imacd_228 <= l_imacd_236) {
      l_text_76 = "-";
      l_color_0 = Tomato;
   }
   if (l_imacd_228 > l_imacd_236 && l_imacd_228 > 0.0) {
      l_text_76 = "-";
      l_color_0 = Lime;
   }
   if (l_imacd_228 <= l_imacd_236 && l_imacd_228 < 0.0) {
      l_text_76 = "-";
      l_color_0 = Red;
   }
   if (Corner_of_Chart_RIGHT_TOP == 1) {
      ObjectCreate("Numbers", OBJ_LABEL, 0, 0, 0);
      ObjectSetText("Numbers", " M1     M5    M15   M30   H1    H4    D1", 6, "Tahoma Narrow", g_color_108);
      ObjectSet("Numbers", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
      ObjectSet("Numbers", OBJPROP_XDISTANCE, gi_104 + 19);
      ObjectSet("Numbers", OBJPROP_YDISTANCE, gi_100 + 25);
   }
   if (Corner_of_Chart_RIGHT_TOP == 0) {
      ObjectCreate("Numbers", OBJ_LABEL, 0, 0, 0);
      ObjectSetText("Numbers", "D1     H4    H1    M30   M15    M5    M1", 6, "Tahoma Narrow", g_color_108);
      ObjectSet("Numbers", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
      ObjectSet("Numbers", OBJPROP_XDISTANCE, gi_104 + 15);
      ObjectSet("Numbers", OBJPROP_YDISTANCE, gi_100 + 25);
   }
   ObjectCreate("SSignalMACDM1t", OBJ_LABEL, 0, 0, 0);
   ObjectSetText("SSignalMACDM1t", "MACD", 6, "Tahoma Narrow", g_color_108);
   ObjectSet("SSignalMACDM1t", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
   ObjectSet("SSignalMACDM1t", OBJPROP_XDISTANCE, gi_104 + 155);
   ObjectSet("SSignalMACDM1t", OBJPROP_YDISTANCE, gi_100 + 35);
   ObjectCreate("SSignalMACDM1", OBJ_LABEL, 0, 0, 0);
   ObjectSetText("SSignalMACDM1", l_text_100, 45, "Tahoma Narrow", l_color_12);
   ObjectSet("SSignalMACDM1", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
   ObjectSet("SSignalMACDM1", OBJPROP_XDISTANCE, gi_104 + 130);
   ObjectSet("SSignalMACDM1", OBJPROP_YDISTANCE, gi_100 + 2);
   ObjectCreate("SSignalMACDM5", OBJ_LABEL, 0, 0, 0);
   ObjectSetText("SSignalMACDM5", l_text_108, 45, "Tahoma Narrow", l_color_16);
   ObjectSet("SSignalMACDM5", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
   ObjectSet("SSignalMACDM5", OBJPROP_XDISTANCE, gi_104 + 110);
   ObjectSet("SSignalMACDM5", OBJPROP_YDISTANCE, gi_100 + 2);
   ObjectCreate("SSignalMACDM15", OBJ_LABEL, 0, 0, 0);
   ObjectSetText("SSignalMACDM15", l_text_116, 45, "Tahoma Narrow", l_color_20);
   ObjectSet("SSignalMACDM15", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
   ObjectSet("SSignalMACDM15", OBJPROP_XDISTANCE, gi_104 + 90);
   ObjectSet("SSignalMACDM15", OBJPROP_YDISTANCE, gi_100 + 2);
   ObjectCreate("SSignalMACDM30", OBJ_LABEL, 0, 0, 0);
   ObjectSetText("SSignalMACDM30", l_text_124, 45, "Tahoma Narrow", l_color_24);
   ObjectSet("SSignalMACDM30", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
   ObjectSet("SSignalMACDM30", OBJPROP_XDISTANCE, gi_104 + 70);
   ObjectSet("SSignalMACDM30", OBJPROP_YDISTANCE, gi_100 + 2);
   ObjectCreate("SSignalMACDH1", OBJ_LABEL, 0, 0, 0);
   ObjectSetText("SSignalMACDH1", l_text_84, 45, "Tahoma Narrow", l_color_4);
   ObjectSet("SSignalMACDH1", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
   ObjectSet("SSignalMACDH1", OBJPROP_XDISTANCE, gi_104 + 50);
   ObjectSet("SSignalMACDH1", OBJPROP_YDISTANCE, gi_100 + 2);
   ObjectCreate("SSignalMACDH4", OBJ_LABEL, 0, 0, 0);
   ObjectSetText("SSignalMACDH4", l_text_92, 45, "Tahoma Narrow", l_color_8);
   ObjectSet("SSignalMACDH4", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
   ObjectSet("SSignalMACDH4", OBJPROP_XDISTANCE, gi_104 + 30);
   ObjectSet("SSignalMACDH4", OBJPROP_YDISTANCE, gi_100 + 2);
   ObjectCreate("SSignalMACDD1", OBJ_LABEL, 0, 0, 0);
   ObjectSetText("SSignalMACDD1", l_text_76, 45, "Tahoma Narrow", l_color_0);
   ObjectSet("SSignalMACDD1", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
   ObjectSet("SSignalMACDD1", OBJPROP_XDISTANCE, gi_104 + 10);
   ObjectSet("SSignalMACDD1", OBJPROP_YDISTANCE, gi_100 + 2);
   double l_irsi_244 = iRSI(NULL, PERIOD_D1, g_period_132, g_applied_price_136, 0);
   double l_irsi_252 = iRSI(NULL, PERIOD_H4, g_period_132, g_applied_price_136, 0);
   double l_irsi_260 = iRSI(NULL, PERIOD_H1, g_period_132, g_applied_price_136, 0);
   double l_irsi_268 = iRSI(NULL, PERIOD_M30, g_period_132, g_applied_price_136, 0);
   double l_irsi_276 = iRSI(NULL, PERIOD_M15, g_period_132, g_applied_price_136, 0);
   double l_irsi_284 = iRSI(NULL, PERIOD_M5, g_period_132, g_applied_price_136, 0);
   double l_irsi_292 = iRSI(NULL, PERIOD_M1, g_period_132, g_applied_price_136, 0);
   double l_istochastic_300 = iStochastic(NULL, PERIOD_D1, g_period_148, g_period_152, g_slowing_156, g_ma_method_160, 0, MODE_MAIN, 0);
   double l_istochastic_308 = iStochastic(NULL, PERIOD_H4, g_period_148, g_period_152, g_slowing_156, g_ma_method_160, 0, MODE_MAIN, 0);
   double l_istochastic_316 = iStochastic(NULL, PERIOD_H1, g_period_148, g_period_152, g_slowing_156, g_ma_method_160, 0, MODE_MAIN, 0);
   double l_istochastic_324 = iStochastic(NULL, PERIOD_M30, g_period_148, g_period_152, g_slowing_156, g_ma_method_160, 0, MODE_MAIN, 0);
   double l_istochastic_332 = iStochastic(NULL, PERIOD_M15, g_period_148, g_period_152, g_slowing_156, g_ma_method_160, 0, MODE_MAIN, 0);
   double l_istochastic_340 = iStochastic(NULL, PERIOD_M5, g_period_148, g_period_152, g_slowing_156, g_ma_method_160, 0, MODE_MAIN, 0);
   double l_istochastic_348 = iStochastic(NULL, PERIOD_M1, g_period_148, g_period_152, g_slowing_156, g_ma_method_160, 0, MODE_MAIN, 0);
   double l_icci_356 = iCCI(NULL, PERIOD_D1, g_period_140, g_applied_price_144, 0);
   double l_icci_364 = iCCI(NULL, PERIOD_H4, g_period_140, g_applied_price_144, 0);
   double l_icci_372 = iCCI(NULL, PERIOD_H1, g_period_140, g_applied_price_144, 0);
   double l_icci_380 = iCCI(NULL, PERIOD_M30, g_period_140, g_applied_price_144, 0);
   double l_icci_388 = iCCI(NULL, PERIOD_M15, g_period_140, g_applied_price_144, 0);
   double l_icci_396 = iCCI(NULL, PERIOD_M5, g_period_140, g_applied_price_144, 0);
   double l_icci_404 = iCCI(NULL, PERIOD_M1, g_period_140, g_applied_price_144, 0);
   string l_text_412 = "";
   string l_text_420 = "";
   string l_text_428 = "";
   string l_text_436 = "";
   string l_text_444 = "";
   string l_text_452 = "";
   string l_text_460 = "";
   string ls_unused_468 = "";
   l_text_460 = "-";
   color l_color_476 = Orange;
   l_text_444 = "-";
   color l_color_480 = Orange;
   l_text_412 = "-";
   color l_color_484 = Orange;
   l_text_452 = "-";
   color l_color_488 = Orange;
   l_text_420 = "-";
   color l_color_492 = Orange;
   l_text_428 = "-";
   color l_color_496 = Orange;
   l_text_436 = "-";
   color l_color_500 = Orange;
   if (l_irsi_244 > 50.0 && l_istochastic_300 > 40.0 && l_icci_356 > 0.0) {
      l_text_460 = "-";
      l_color_476 = Lime;
   }
   if (l_irsi_252 > 50.0 && l_istochastic_308 > 40.0 && l_icci_364 > 0.0) {
      l_text_444 = "-";
      l_color_480 = Lime;
   }
   if (l_irsi_260 > 50.0 && l_istochastic_316 > 40.0 && l_icci_372 > 0.0) {
      l_text_412 = "-";
      l_color_484 = Lime;
   }
   if (l_irsi_268 > 50.0 && l_istochastic_324 > 40.0 && l_icci_380 > 0.0) {
      l_text_452 = "-";
      l_color_488 = Lime;
   }
   if (l_irsi_276 > 50.0 && l_istochastic_332 > 40.0 && l_icci_388 > 0.0) {
      l_text_420 = "-";
      l_color_492 = Lime;
   }
   if (l_irsi_284 > 50.0 && l_istochastic_340 > 40.0 && l_icci_396 > 0.0) {
      l_text_428 = "-";
      l_color_496 = Lime;
   }
   if (l_irsi_292 > 50.0 && l_istochastic_348 > 40.0 && l_icci_404 > 0.0) {
      l_text_436 = "-";
      l_color_500 = Lime;
   }
   if (l_irsi_244 < 50.0 && l_istochastic_300 < 60.0 && l_icci_356 < 0.0) {
      l_text_460 = "-";
      l_color_476 = Red;
   }
   if (l_irsi_252 < 50.0 && l_istochastic_308 < 60.0 && l_icci_364 < 0.0) {
      l_text_444 = "-";
      l_color_480 = Red;
   }
   if (l_irsi_260 < 50.0 && l_istochastic_316 < 60.0 && l_icci_372 < 0.0) {
      l_text_412 = "-";
      l_color_484 = Red;
   }
   if (l_irsi_268 < 50.0 && l_istochastic_324 < 60.0 && l_icci_380 < 0.0) {
      l_text_452 = "-";
      l_color_488 = Red;
   }
   if (l_irsi_276 < 50.0 && l_istochastic_332 < 60.0 && l_icci_388 < 0.0) {
      l_text_420 = "-";
      l_color_492 = Red;
   }
   if (l_irsi_284 < 50.0 && l_istochastic_340 < 60.0 && l_icci_396 < 0.0) {
      l_text_428 = "-";
      l_color_496 = Red;
   }
   if (l_irsi_292 < 50.0 && l_istochastic_348 < 60.0 && l_icci_404 < 0.0) {
      l_text_436 = "-";
      l_color_500 = Red;
   }
   ObjectCreate("SignalSTRM1t", OBJ_LABEL, 0, 0, 0);
   ObjectSetText("SignalSTRM1t", "STR", 6, "Tahoma Narrow", g_color_108);
   ObjectSet("SignalSTRM1t", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
   ObjectSet("SignalSTRM1t", OBJPROP_XDISTANCE, gi_104 + 155);
   ObjectSet("SignalSTRM1t", OBJPROP_YDISTANCE, gi_100 + 43);
   ObjectCreate("SignalSTRM1", OBJ_LABEL, 0, 0, 0);
   ObjectSetText("SignalSTRM1", l_text_436, 45, "Tahoma Narrow", l_color_500);
   ObjectSet("SignalSTRM1", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
   ObjectSet("SignalSTRM1", OBJPROP_XDISTANCE, gi_104 + 130);
   ObjectSet("SignalSTRM1", OBJPROP_YDISTANCE, gi_100 + 10);
   ObjectCreate("SignalSTRM5", OBJ_LABEL, 0, 0, 0);
   ObjectSetText("SignalSTRM5", l_text_428, 45, "Tahoma Narrow", l_color_496);
   ObjectSet("SignalSTRM5", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
   ObjectSet("SignalSTRM5", OBJPROP_XDISTANCE, gi_104 + 110);
   ObjectSet("SignalSTRM5", OBJPROP_YDISTANCE, gi_100 + 10);
   ObjectCreate("SignalSTRM15", OBJ_LABEL, 0, 0, 0);
   ObjectSetText("SignalSTRM15", l_text_420, 45, "Tahoma Narrow", l_color_492);
   ObjectSet("SignalSTRM15", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
   ObjectSet("SignalSTRM15", OBJPROP_XDISTANCE, gi_104 + 90);
   ObjectSet("SignalSTRM15", OBJPROP_YDISTANCE, gi_100 + 10);
   ObjectCreate("SignalSTRM30", OBJ_LABEL, 0, 0, 0);
   ObjectSetText("SignalSTRM30", l_text_452, 45, "Tahoma Narrow", l_color_488);
   ObjectSet("SignalSTRM30", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
   ObjectSet("SignalSTRM30", OBJPROP_XDISTANCE, gi_104 + 70);
   ObjectSet("SignalSTRM30", OBJPROP_YDISTANCE, gi_100 + 10);
   ObjectCreate("SignalSTRM60", OBJ_LABEL, 0, 0, 0);
   ObjectSetText("SignalSTRM60", l_text_412, 45, "Tahoma Narrow", l_color_484);
   ObjectSet("SignalSTRM60", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
   ObjectSet("SignalSTRM60", OBJPROP_XDISTANCE, gi_104 + 50);
   ObjectSet("SignalSTRM60", OBJPROP_YDISTANCE, gi_100 + 10);
   ObjectCreate("SignalSTRM240", OBJ_LABEL, 0, 0, 0);
   ObjectSetText("SignalSTRM240", l_text_444, 45, "Tahoma Narrow", l_color_480);
   ObjectSet("SignalSTRM240", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
   ObjectSet("SignalSTRM240", OBJPROP_XDISTANCE, gi_104 + 30);
   ObjectSet("SignalSTRM240", OBJPROP_YDISTANCE, gi_100 + 10);
   ObjectCreate("SignalSTRM1440", OBJ_LABEL, 0, 0, 0);
   ObjectSetText("SignalSTRM1440", l_text_460, 45, "Tahoma Narrow", l_color_476);
   ObjectSet("SignalSTRM1440", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
   ObjectSet("SignalSTRM1440", OBJPROP_XDISTANCE, gi_104 + 10);
   ObjectSet("SignalSTRM1440", OBJPROP_YDISTANCE, gi_100 + 10);
   double l_ima_504 = iMA(Symbol(), PERIOD_M1, g_period_164, 0, g_ma_method_172, g_applied_price_176, 0);
   double l_ima_512 = iMA(Symbol(), PERIOD_M1, g_period_168, 0, g_ma_method_172, g_applied_price_176, 0);
   double l_ima_520 = iMA(Symbol(), PERIOD_M5, g_period_164, 0, g_ma_method_172, g_applied_price_176, 0);
   double l_ima_528 = iMA(Symbol(), PERIOD_M5, g_period_168, 0, g_ma_method_172, g_applied_price_176, 0);
   double l_ima_536 = iMA(Symbol(), PERIOD_M15, g_period_164, 0, g_ma_method_172, g_applied_price_176, 0);
   double l_ima_544 = iMA(Symbol(), PERIOD_M15, g_period_168, 0, g_ma_method_172, g_applied_price_176, 0);
   double l_ima_552 = iMA(Symbol(), PERIOD_M30, g_period_164, 0, g_ma_method_172, g_applied_price_176, 0);
   double l_ima_560 = iMA(Symbol(), PERIOD_M30, g_period_168, 0, g_ma_method_172, g_applied_price_176, 0);
   double l_ima_568 = iMA(Symbol(), PERIOD_H1, g_period_164, 0, g_ma_method_172, g_applied_price_176, 0);
   double l_ima_576 = iMA(Symbol(), PERIOD_H1, g_period_168, 0, g_ma_method_172, g_applied_price_176, 0);
   double l_ima_584 = iMA(Symbol(), PERIOD_H4, g_period_164, 0, g_ma_method_172, g_applied_price_176, 0);
   double l_ima_592 = iMA(Symbol(), PERIOD_H4, g_period_168, 0, g_ma_method_172, g_applied_price_176, 0);
   double l_ima_600 = iMA(Symbol(), PERIOD_D1, g_period_164, 0, g_ma_method_172, g_applied_price_176, 0);
   double l_ima_608 = iMA(Symbol(), PERIOD_D1, g_period_168, 0, g_ma_method_172, g_applied_price_176, 0);
   string l_text_616 = "";
   string l_text_624 = "";
   string l_text_632 = "";
   string l_text_640 = "";
   string l_text_648 = "";
   string l_text_656 = "";
   string l_text_664 = "";
   if (l_ima_504 > l_ima_512) {
      l_text_616 = "-";
      l_color_28 = Lime;
   }
   if (l_ima_504 <= l_ima_512) {
      l_text_616 = "-";
      l_color_28 = Red;
   }
   if (l_ima_520 > l_ima_528) {
      l_text_624 = "-";
      l_color_32 = Lime;
   }
   if (l_ima_520 <= l_ima_528) {
      l_text_624 = "-";
      l_color_32 = Red;
   }
   if (l_ima_536 > l_ima_544) {
      l_text_632 = "-";
      l_color_36 = Lime;
   }
   if (l_ima_536 <= l_ima_544) {
      l_text_632 = "-";
      l_color_36 = Red;
   }
   if (l_ima_552 > l_ima_560) {
      l_text_640 = "-";
      l_color_40 = Lime;
   }
   if (l_ima_552 <= l_ima_560) {
      l_text_640 = "-";
      l_color_40 = Red;
   }
   if (l_ima_568 > l_ima_576) {
      l_text_648 = "-";
      l_color_44 = Lime;
   }
   if (l_ima_568 <= l_ima_576) {
      l_text_648 = "-";
      l_color_44 = Red;
   }
   if (l_ima_584 > l_ima_592) {
      l_text_656 = "-";
      l_color_48 = Lime;
   }
   if (l_ima_584 <= l_ima_592) {
      l_text_656 = "-";
      l_color_48 = Red;
   }
   if (l_ima_600 > l_ima_608) {
      l_text_664 = "-";
      l_color_52 = Lime;
   }
   if (l_ima_600 <= l_ima_608) {
      l_text_664 = "-";
      l_color_52 = Red;
   }
   ObjectCreate("SignalEMAM1t", OBJ_LABEL, 0, 0, 0);
   ObjectSetText("SignalEMAM1t", "EMA", 6, "Tahoma Narrow", g_color_108);
   ObjectSet("SignalEMAM1t", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
   ObjectSet("SignalEMAM1t", OBJPROP_XDISTANCE, gi_104 + 155);
   ObjectSet("SignalEMAM1t", OBJPROP_YDISTANCE, gi_100 + 51);
   ObjectCreate("SignalEMAM1", OBJ_LABEL, 0, 0, 0);
   ObjectSetText("SignalEMAM1", l_text_616, 45, "Tahoma Narrow", l_color_28);
   ObjectSet("SignalEMAM1", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
   ObjectSet("SignalEMAM1", OBJPROP_XDISTANCE, gi_104 + 130);
   ObjectSet("SignalEMAM1", OBJPROP_YDISTANCE, gi_100 + 18);
   ObjectCreate("SignalEMAM5", OBJ_LABEL, 0, 0, 0);
   ObjectSetText("SignalEMAM5", l_text_624, 45, "Tahoma Narrow", l_color_32);
   ObjectSet("SignalEMAM5", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
   ObjectSet("SignalEMAM5", OBJPROP_XDISTANCE, gi_104 + 110);
   ObjectSet("SignalEMAM5", OBJPROP_YDISTANCE, gi_100 + 18);
   ObjectCreate("SignalEMAM15", OBJ_LABEL, 0, 0, 0);
   ObjectSetText("SignalEMAM15", l_text_632, 45, "Tahoma Narrow", l_color_36);
   ObjectSet("SignalEMAM15", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
   ObjectSet("SignalEMAM15", OBJPROP_XDISTANCE, gi_104 + 90);
   ObjectSet("SignalEMAM15", OBJPROP_YDISTANCE, gi_100 + 18);
   ObjectCreate("SignalEMAM30", OBJ_LABEL, 0, 0, 0);
   ObjectSetText("SignalEMAM30", l_text_640, 45, "Tahoma Narrow", l_color_40);
   ObjectSet("SignalEMAM30", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
   ObjectSet("SignalEMAM30", OBJPROP_XDISTANCE, gi_104 + 70);
   ObjectSet("SignalEMAM30", OBJPROP_YDISTANCE, gi_100 + 18);
   ObjectCreate("SignalEMAM60", OBJ_LABEL, 0, 0, 0);
   ObjectSetText("SignalEMAM60", l_text_648, 45, "Tahoma Narrow", l_color_44);
   ObjectSet("SignalEMAM60", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
   ObjectSet("SignalEMAM60", OBJPROP_XDISTANCE, gi_104 + 50);
   ObjectSet("SignalEMAM60", OBJPROP_YDISTANCE, gi_100 + 18);
   ObjectCreate("SignalEMAM240", OBJ_LABEL, 0, 0, 0);
   ObjectSetText("SignalEMAM240", l_text_656, 45, "Tahoma Narrow", l_color_48);
   ObjectSet("SignalEMAM240", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
   ObjectSet("SignalEMAM240", OBJPROP_XDISTANCE, gi_104 + 30);
   ObjectSet("SignalEMAM240", OBJPROP_YDISTANCE, gi_100 + 18);
   ObjectCreate("SignalEMAM1440", OBJ_LABEL, 0, 0, 0);
   ObjectSetText("SignalEMAM1440", l_text_664, 45, "Tahoma Narrow", l_color_52);
   ObjectSet("SignalEMAM1440", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
   ObjectSet("SignalEMAM1440", OBJPROP_XDISTANCE, gi_104 + 10);
   ObjectSet("SignalEMAM1440", OBJPROP_YDISTANCE, gi_100 + 18);
   double l_ima_672 = iMA(Symbol(), 0, 1, 0, MODE_EMA, PRICE_CLOSE, 0);
   string l_dbl2str_680 = DoubleToStr(l_ima_672, Digits);
   if (Show_Smaller_Size == FALSE) {
      if (Show_Price == TRUE) {
         ObjectCreate("Signalprice", OBJ_LABEL, 0, 0, 0);
         ObjectSetText("Signalprice", "" + l_dbl2str_680 + "", 33, "Arial", l_color_488);
         ObjectSet("Signalprice", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
         ObjectSet("Signalprice", OBJPROP_XDISTANCE, gi_104 + 10);
         ObjectSet("Signalprice", OBJPROP_YDISTANCE, gi_100 + 58);
      }
   }
   if (Show_Smaller_Size == TRUE) {
      if (Show_Price == TRUE) {
         ObjectCreate("Signalprice", OBJ_LABEL, 0, 0, 0);
         ObjectSetText("Signalprice", "" + l_dbl2str_680 + "", 15, "Arial", l_color_488);
         ObjectSet("Signalprice", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
         ObjectSet("Signalprice", OBJPROP_XDISTANCE, gi_104 + 10);
         ObjectSet("Signalprice", OBJPROP_YDISTANCE, gi_100 + 60);
      }
   }
   int li_688 = 0;
   int li_692 = 0;
   int li_696 = 0;
   int li_700 = 0;
   int li_704 = 0;
   int li_708 = 0;
   li_688 = (iHigh(NULL, PERIOD_D1, 1) - iLow(NULL, PERIOD_D1, 1)) / Point;
   for (li_708 = 1; li_708 <= 5; li_708++) li_692 = li_692 + (iHigh(NULL, PERIOD_D1, li_708) - iLow(NULL, PERIOD_D1, li_708)) / Point;
   for (li_708 = 1; li_708 <= 10; li_708++) li_696 = li_696 + (iHigh(NULL, PERIOD_D1, li_708) - iLow(NULL, PERIOD_D1, li_708)) / Point;
   for (li_708 = 1; li_708 <= 20; li_708++) li_700 = li_700 + (iHigh(NULL, PERIOD_D1, li_708) - iLow(NULL, PERIOD_D1, li_708)) / Point;
   li_692 /= 5;
   li_696 /= 10;
   li_700 /= 20;
   li_704 = (li_688 + li_692 + li_696 + li_700) / 4;
   string ls_unused_712 = "";
   string ls_unused_720 = "";
   string l_dbl2str_728 = "";
   string l_dbl2str_736 = "";
   string l_dbl2str_744 = "";
   string l_dbl2str_752 = "";
   string ls_unused_760 = "";
   string ls_unused_768 = "";
   string ls_776 = "";
   double l_iopen_784 = iOpen(NULL, PERIOD_D1, 0);
   double l_iclose_792 = iClose(NULL, PERIOD_D1, 0);
   double ld_800 = (Ask - Bid) / Point;
   double l_ihigh_808 = iHigh(NULL, PERIOD_D1, 0);
   double l_ilow_816 = iLow(NULL, PERIOD_D1, 0);
   l_dbl2str_736 = DoubleToStr((l_iclose_792 - l_iopen_784) / Point, 0);
   l_dbl2str_728 = DoubleToStr(ld_800, Digits - 4);
   l_dbl2str_744 = DoubleToStr(li_704, Digits - 4);
   ls_776 = (iHigh(NULL, PERIOD_D1, 1) - iLow(NULL, PERIOD_D1, 1)) / Point;
   l_dbl2str_752 = DoubleToStr((l_ihigh_808 - l_ilow_816) / Point, 0);
   if (l_iclose_792 >= l_iopen_784) {
      ls_unused_760 = "-";
      l_color_64 = Lime;
   }
   if (l_iclose_792 < l_iopen_784) {
      ls_unused_760 = "-";
      l_color_64 = OrangeRed;
   }
   if (l_dbl2str_744 > ls_776) {
      ls_unused_768 = "-";
      l_color_68 = Lime;
   }
   if (l_dbl2str_744 < ls_776) {
      ls_unused_768 = "-";
      l_color_68 = OrangeRed;
   }
   if (Show_Smaller_Size == FALSE) {
      if (Show_Xtra_Details == TRUE) {
         if (Show_Price == TRUE) {
            ObjectCreate("MMLEVELS7", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS7", "Spread", 12, "Arial", g_color_112);
            ObjectSet("MMLEVELS7", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS7", OBJPROP_XDISTANCE, gi_104 + 45);
            ObjectSet("MMLEVELS7", OBJPROP_YDISTANCE, gi_100 + 100);
            ObjectCreate("MMLEVELS8", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS8", "" + l_dbl2str_728 + "", 12, "Arial Bold", Gold);
            ObjectSet("MMLEVELS8", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS8", OBJPROP_XDISTANCE, gi_104 + 10);
            ObjectSet("MMLEVELS8", OBJPROP_YDISTANCE, gi_100 + 100);
            ObjectCreate("MMLEVELS9", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS9", "Pips to Open", 12, "Arial", g_color_112);
            ObjectSet("MMLEVELS9", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS9", OBJPROP_XDISTANCE, gi_104 + 45);
            ObjectSet("MMLEVELS9", OBJPROP_YDISTANCE, gi_100 + 115);
            ObjectCreate("MMLEVELS10", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS10", "" + l_dbl2str_736 + "", 12, "Arial Bold", l_color_64);
            ObjectSet("MMLEVELS10", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS10", OBJPROP_XDISTANCE, gi_104 + 10);
            ObjectSet("MMLEVELS10", OBJPROP_YDISTANCE, gi_100 + 115);
            ObjectCreate("MMLEVELS11", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS11", "Hi to Low", 12, "Arial", g_color_112);
            ObjectSet("MMLEVELS11", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS11", OBJPROP_XDISTANCE, gi_104 + 45);
            ObjectSet("MMLEVELS11", OBJPROP_YDISTANCE, gi_100 + 130);
            ObjectCreate("MMLEVELS12", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS12", "" + l_dbl2str_752 + "", 12, "Arial Bold", Gold);
            ObjectSet("MMLEVELS12", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS12", OBJPROP_XDISTANCE, gi_104 + 10);
            ObjectSet("MMLEVELS12", OBJPROP_YDISTANCE, gi_100 + 130);
            ObjectCreate("MMLEVELS13", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS13", "Daily Av", 12, "Arial", g_color_112);
            ObjectSet("MMLEVELS13", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS13", OBJPROP_XDISTANCE, gi_104 + 45);
            ObjectSet("MMLEVELS13", OBJPROP_YDISTANCE, gi_100 + 145);
            ObjectCreate("MMLEVELS14", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS14", "" + l_dbl2str_744 + "", 12, "Arial Bold", l_color_68);
            ObjectSet("MMLEVELS14", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS14", OBJPROP_XDISTANCE, gi_104 + 10);
            ObjectSet("MMLEVELS14", OBJPROP_YDISTANCE, gi_100 + 145);
         }
      }
   }
   if (Show_Smaller_Size == FALSE) {
      if (Show_Xtra_Details == TRUE) {
         if (Show_Price == FALSE) {
            ObjectCreate("MMLEVELS7", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS7", "Spread", 12, "Arial", g_color_112);
            ObjectSet("MMLEVELS7", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS7", OBJPROP_XDISTANCE, gi_104 + 45);
            ObjectSet("MMLEVELS7", OBJPROP_YDISTANCE, gi_100 + 60);
            ObjectCreate("MMLEVELS8", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS8", "" + l_dbl2str_728 + "", 12, "Arial Bold", Gold);
            ObjectSet("MMLEVELS8", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS8", OBJPROP_XDISTANCE, gi_104 + 10);
            ObjectSet("MMLEVELS8", OBJPROP_YDISTANCE, gi_100 + 60);
            ObjectCreate("MMLEVELS9", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS9", "Pips to Open", 12, "Arial", g_color_112);
            ObjectSet("MMLEVELS9", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS9", OBJPROP_XDISTANCE, gi_104 + 45);
            ObjectSet("MMLEVELS9", OBJPROP_YDISTANCE, gi_100 + 75);
            ObjectCreate("MMLEVELS10", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS10", "" + l_dbl2str_736 + "", 12, "Arial Bold", l_color_64);
            ObjectSet("MMLEVELS10", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS10", OBJPROP_XDISTANCE, gi_104 + 10);
            ObjectSet("MMLEVELS10", OBJPROP_YDISTANCE, gi_100 + 75);
            ObjectCreate("MMLEVELS11", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS11", "Hi to Low", 12, "Arial", g_color_112);
            ObjectSet("MMLEVELS11", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS11", OBJPROP_XDISTANCE, gi_104 + 45);
            ObjectSet("MMLEVELS11", OBJPROP_YDISTANCE, gi_100 + 90);
            ObjectCreate("MMLEVELS12", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS12", "" + l_dbl2str_752 + "", 12, "Arial Bold", Gold);
            ObjectSet("MMLEVELS12", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS12", OBJPROP_XDISTANCE, gi_104 + 10);
            ObjectSet("MMLEVELS12", OBJPROP_YDISTANCE, gi_100 + 90);
            ObjectCreate("MMLEVELS13", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS13", "Daily Av", 12, "Arial", g_color_112);
            ObjectSet("MMLEVELS13", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS13", OBJPROP_XDISTANCE, gi_104 + 45);
            ObjectSet("MMLEVELS13", OBJPROP_YDISTANCE, gi_100 + 105);
            ObjectCreate("MMLEVELS14", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS14", "" + l_dbl2str_744 + "", 12, "Arial Bold", l_color_68);
            ObjectSet("MMLEVELS14", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS14", OBJPROP_XDISTANCE, gi_104 + 10);
            ObjectSet("MMLEVELS14", OBJPROP_YDISTANCE, gi_100 + 105);
         }
      }
   }
   if (Show_Smaller_Size == TRUE) {
      if (Show_Xtra_Details == TRUE) {
         if (Show_Price == TRUE) {
            ObjectCreate("MMLEVELS7", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS7", "Spread", 9, "Arial", g_color_112);
            ObjectSet("MMLEVELS7", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS7", OBJPROP_XDISTANCE, gi_104 + 40);
            ObjectSet("MMLEVELS7", OBJPROP_YDISTANCE, gi_100 + 80);
            ObjectCreate("MMLEVELS8", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS8", "" + l_dbl2str_728 + "", 9, "Arial Bold", Gold);
            ObjectSet("MMLEVELS8", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS8", OBJPROP_XDISTANCE, gi_104 + 10);
            ObjectSet("MMLEVELS8", OBJPROP_YDISTANCE, gi_100 + 80);
            ObjectCreate("MMLEVELS9", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS9", "Pips to Open", 9, "Arial", g_color_112);
            ObjectSet("MMLEVELS9", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS9", OBJPROP_XDISTANCE, gi_104 + 40);
            ObjectSet("MMLEVELS9", OBJPROP_YDISTANCE, gi_100 + 95);
            ObjectCreate("MMLEVELS10", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS10", "" + l_dbl2str_736 + "", 9, "Arial Bold", l_color_64);
            ObjectSet("MMLEVELS10", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS10", OBJPROP_XDISTANCE, gi_104 + 10);
            ObjectSet("MMLEVELS10", OBJPROP_YDISTANCE, gi_100 + 95);
            ObjectCreate("MMLEVELS11", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS11", "Hi to Low", 9, "Arial", g_color_112);
            ObjectSet("MMLEVELS11", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS11", OBJPROP_XDISTANCE, gi_104 + 40);
            ObjectSet("MMLEVELS11", OBJPROP_YDISTANCE, gi_100 + 110);
            ObjectCreate("MMLEVELS12", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS12", "" + l_dbl2str_752 + "", 9, "Arial Bold", Gold);
            ObjectSet("MMLEVELS12", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS12", OBJPROP_XDISTANCE, gi_104 + 10);
            ObjectSet("MMLEVELS12", OBJPROP_YDISTANCE, gi_100 + 110);
            ObjectCreate("MMLEVELS13", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS13", "Daily Av", 9, "Arial", g_color_112);
            ObjectSet("MMLEVELS13", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS13", OBJPROP_XDISTANCE, gi_104 + 40);
            ObjectSet("MMLEVELS13", OBJPROP_YDISTANCE, gi_100 + 125);
            ObjectCreate("MMLEVELS14", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS14", "" + l_dbl2str_744 + "", 9, "Arial Bold", l_color_68);
            ObjectSet("MMLEVELS14", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS14", OBJPROP_XDISTANCE, gi_104 + 10);
            ObjectSet("MMLEVELS14", OBJPROP_YDISTANCE, gi_100 + 125);
         }
      }
   }
   if (Show_Smaller_Size == TRUE) {
      if (Show_Xtra_Details == TRUE) {
         if (Show_Price == FALSE) {
            ObjectCreate("MMLEVELS7", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS7", "Spread", 9, "Arial", g_color_112);
            ObjectSet("MMLEVELS7", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS7", OBJPROP_XDISTANCE, gi_104 + 40);
            ObjectSet("MMLEVELS7", OBJPROP_YDISTANCE, gi_100 + 60);
            ObjectCreate("MMLEVELS8", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS8", "" + l_dbl2str_728 + "", 9, "Arial Bold", Gold);
            ObjectSet("MMLEVELS8", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS8", OBJPROP_XDISTANCE, gi_104 + 10);
            ObjectSet("MMLEVELS8", OBJPROP_YDISTANCE, gi_100 + 60);
            ObjectCreate("MMLEVELS9", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS9", "Pips to Open", 9, "Arial", g_color_112);
            ObjectSet("MMLEVELS9", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS9", OBJPROP_XDISTANCE, gi_104 + 40);
            ObjectSet("MMLEVELS9", OBJPROP_YDISTANCE, gi_100 + 75);
            ObjectCreate("MMLEVELS10", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS10", "" + l_dbl2str_736 + "", 9, "Arial Bold", l_color_64);
            ObjectSet("MMLEVELS10", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS10", OBJPROP_XDISTANCE, gi_104 + 10);
            ObjectSet("MMLEVELS10", OBJPROP_YDISTANCE, gi_100 + 75);
            ObjectCreate("MMLEVELS11", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS11", "Hi to Low", 9, "Arial", g_color_112);
            ObjectSet("MMLEVELS11", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS11", OBJPROP_XDISTANCE, gi_104 + 40);
            ObjectSet("MMLEVELS11", OBJPROP_YDISTANCE, gi_100 + 90);
            ObjectCreate("MMLEVELS12", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS12", "" + l_dbl2str_752 + "", 9, "Arial Bold", Gold);
            ObjectSet("MMLEVELS12", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS12", OBJPROP_XDISTANCE, gi_104 + 10);
            ObjectSet("MMLEVELS12", OBJPROP_YDISTANCE, gi_100 + 90);
            ObjectCreate("MMLEVELS13", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS13", "Daily Av", 9, "Arial", g_color_112);
            ObjectSet("MMLEVELS13", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS13", OBJPROP_XDISTANCE, gi_104 + 40);
            ObjectSet("MMLEVELS13", OBJPROP_YDISTANCE, gi_100 + 105);
            ObjectCreate("MMLEVELS14", OBJ_LABEL, 0, 0, 0);
            ObjectSetText("MMLEVELS14", "" + l_dbl2str_744 + "", 9, "Arial Bold", l_color_68);
            ObjectSet("MMLEVELS14", OBJPROP_CORNER, Corner_of_Chart_RIGHT_TOP);
            ObjectSet("MMLEVELS14", OBJPROP_XDISTANCE, gi_104 + 10);
            ObjectSet("MMLEVELS14", OBJPROP_YDISTANCE, gi_100 + 105);
         }
      }
   }
   return (0);
}