/*
   Generated by EX4-TO-MQ4 decompiler V4.0.224.1 []
   Website: http://purebeam.biz
   E-mail : purebeam@gmail.com
*/

#property indicator_chart_window

extern string note1 = "Change font colors automatically? True = Yes";
extern bool Bid_Ask_Colors = FALSE;
extern string note2 = "Default Font Color";
extern color FontColor = Black;
extern string note3 = "Font Size";
extern int FontSize = 12;
extern string note4 = "Font Type";
extern string FontType = "Arial Bold";
extern string note5 = "Display the price in what corner?";
extern string note6 = "Upper left=0; Upper right=1";
extern string note7 = "Lower left=2; Lower right=3";
extern int WhatCorner = 2;
double g_bid_156;

int init() {
   return (0);
}

int deinit() {
   ObjectDelete("Market_Price_Label");
   return (0);
}

int start() {
   if (Bid_Ask_Colors == TRUE) {
      if (Bid > g_bid_156) FontColor = LawnGreen;
      if (Bid < g_bid_156) FontColor = Red;
      g_bid_156 = Bid;
   }
   string l_dbl2str_0 = DoubleToStr(Bid, Digits);
   ObjectCreate("Market_Price_Label", OBJ_LABEL, 0, 0, 0);
   ObjectSetText("Market_Price_Label", l_dbl2str_0, FontSize, FontType, FontColor);
   ObjectSet("Market_Price_Label", OBJPROP_CORNER, WhatCorner);
   ObjectSet("Market_Price_Label", OBJPROP_XDISTANCE, 4);
   ObjectSet("Market_Price_Label", OBJPROP_YDISTANCE, 10);
   return (0);
}