#property copyright "Copyright © 2007 Third Wave FX"
#property link      "http://www.thirdwavefx.com"

#property indicator_chart_window

extern string indi_name = "Third Wave FX VENOM - Window 2";
int G_period_84 = 50;
int G_period_88 = 100;

// E37F0136AA3FFAF149B351F6A4C948E9
int init() {
   return (0);
}

// 52D46093050F38C27267BCE42543EF60
int deinit() {
   ObjectsDeleteAll(0, OBJ_LABEL);
   ObjectDelete("Website");
   ObjectDelete("Expiry");
   ObjectDelete("Lock");
   ObjectDelete("BG1");
   ObjectDelete("BG2");
   ObjectDelete("BG3");
   ObjectDelete("BG4");
   ObjectDelete("BG5");
   ObjectDelete("BG6");
   ObjectDelete("BG7");
   ObjectDelete("BG8");
   ObjectDelete("BG9");
   ObjectDelete("BG10");
   ObjectDelete("BG11");
   ObjectDelete("BG12");
   ObjectDelete("BG13");
   ObjectDelete("BG14");
   ObjectDelete("BG15");
   ObjectDelete("BG16");
   ObjectDelete("BG17");
   ObjectDelete("BG18");
   ObjectDelete("Venom_Pair");
   ObjectDelete("Venom_Price");
   ObjectDelete("Venom_Spread");
   ObjectDelete("Buy_Signal");
   ObjectDelete("Buy_Signal1");
   ObjectDelete("Sell_Signal");
   ObjectDelete("Sell_Signal1");
   ObjectDelete("Buy_Price");
   ObjectDelete("Buy_Time");
   ObjectDelete("Sell_Price");
   ObjectDelete("Sell_Time");
   ObjectDelete("1_SR");
   ObjectDelete("2_SR");
   ObjectDelete("3_SR");
   ObjectDelete("4_SR");
   ObjectDelete("Top");
   ObjectDelete("Middle");
   ObjectDelete("Bottom");
   ObjectDelete("Data");
   return (0);
}

// EA2B2676C28C0DB26D39331A336C6B92
int start() {
   double minute_0;
   double hour_8;
   double day_16;
   double month_24;
   double year_32;
   string Ls_40;
   string Ls_48;
   string Ls_56;
   string Ls_64;
   string dbl2str_72;
   double bid_80;
   double digits_88;
   double spread_96;
   string dbl2str_104;
   string dbl2str_112;
   int minute_120;
   int hour_124;
   int day_128;
   string var_name_132;
   string var_name_140;
   int global_var_148;
   int global_var_152;
   double digits_156;
   double bid_164;
   string var_name_172;
   string var_name_180;
   string var_name_188;
   string var_name_196;
   string dbl2str_204;
   string Ls_212;
   string Ls_220;
   int global_var_228;
   double global_var_232;
   double global_var_240;
   double global_var_248;
   string var_name_256;
   string var_name_264;
   string var_name_272;
   string var_name_280;
   string dbl2str_288;
   string Ls_296;
   string Ls_304;
   int global_var_312;
   double global_var_316;
   double global_var_324;
   double global_var_332;
   datetime time_340;
   int Li_344;
   double ima_348;
   double ima_356;
   double ima_364;
   double ima_372;
   double ima_380;
   double ima_388;
   double Ld_396;
   double Ld_404;
   double Ld_412;
   double Ld_420;
   double Ld_428;
   double Ld_436;
   double Ld_444;
   double Ld_452;
   double Ld_460;
   double Ld_468;
   int datetime_476;
   int datetime_480;
   double ima_484;
   double ima_492;
   int datetime_500;
   int datetime_504;
   double ima_508;
   double ima_516;
   int datetime_524;
   int datetime_528;
   ObjectCreate("Name", OBJ_LABEL, 0, 0, 0, 0, 0);
   ObjectSetText("Name", "THIRDWAVEFX", 12, "Verdana", Red);
   ObjectSet("Name", OBJPROP_CORNER, 1);
   ObjectSet("Name", OBJPROP_XDISTANCE, 120);
   ObjectSet("Name", OBJPROP_YDISTANCE, 31);
   ObjectCreate("Name1", OBJ_LABEL, 0, 0, 0, 0, 0);
   ObjectSetText("Name1", "VENOM", 20, "Arial Black", White);
   ObjectSet("Name1", OBJPROP_CORNER, 1);
   ObjectSet("Name1", OBJPROP_XDISTANCE, 4);
   ObjectSet("Name1", OBJPROP_YDISTANCE, 19);
   ObjectCreate("Website", OBJ_LABEL, 0, 0, 0, 0, 0);
   ObjectSetText("Website", "www.thirdwavefx.com", 12, "Verdana", Red);
   ObjectSet("Website", OBJPROP_CORNER, 1);
   ObjectSet("Website", OBJPROP_XDISTANCE, 4);
   ObjectSet("Website", OBJPROP_YDISTANCE, 5);
   ObjectCreate("Expiry", OBJ_LABEL, 0, 0, 0, 0, 0);
   ObjectSetText("Expiry", "Coded By ShahJB", 10, "Arial Narrow", Silver);
   ObjectSet("Expiry", OBJPROP_CORNER, 1);
   ObjectSet("Expiry", OBJPROP_XDISTANCE, 4);
   ObjectSet("Expiry", OBJPROP_YDISTANCE, 53);
   ObjectCreate("Lock", OBJ_LABEL, 0, 0, 0, 0, 0);
   ObjectSetText("Lock", "sharishen@gmail.com", 10, "Arial Narrow", Silver);
   ObjectSet("Lock", OBJPROP_CORNER, 1);
   ObjectSet("Lock", OBJPROP_XDISTANCE, 4);
   ObjectSet("Lock", OBJPROP_YDISTANCE, 70);
   RefreshRates();
   int second_532 = TimeSeconds(TimeCurrent());
   int minute_536 = TimeMinute(TimeCurrent());
   int hour_540 = TimeHour(TimeCurrent());
   int day_544 = TimeDay(TimeCurrent());
   int month_548 = TimeMonth(TimeCurrent());
   int year_552 = TimeYear(TimeCurrent());
   if (year_552 < 2030) {
      ObjectCreate("BG1", OBJ_LABEL, 0, 0, 0, 0, 0);
      ObjectSetText("BG1", "nnnnn", 50, "Wingdings", Black);
      ObjectSet("BG1", OBJPROP_CORNER, 0);
      ObjectSet("BG1", OBJPROP_XDISTANCE, 0);
      ObjectSet("BG1", OBJPROP_YDISTANCE, 0);
      ObjectCreate("BG2", OBJ_LABEL, 0, 0, 0, 0, 0);
      ObjectSetText("BG2", "nnnn", 50, "Wingdings", Black);
      ObjectSet("BG2", OBJPROP_CORNER, 0);
      ObjectSet("BG2", OBJPROP_XDISTANCE, 15);
      ObjectSet("BG2", OBJPROP_YDISTANCE, 0);
      ObjectCreate("BG3", OBJ_LABEL, 0, 0, 0, 0, 0);
      ObjectSetText("BG3", "nnnnn", 50, "Wingdings", Black);
      ObjectSet("BG3", OBJPROP_CORNER, 0);
      ObjectSet("BG3", OBJPROP_XDISTANCE, 0);
      ObjectSet("BG3", OBJPROP_YDISTANCE, 35);
      ObjectCreate("BG4", OBJ_LABEL, 0, 0, 0, 0, 0);
      ObjectSetText("BG4", "nnnn", 50, "Wingdings", Black);
      ObjectSet("BG4", OBJPROP_CORNER, 0);
      ObjectSet("BG4", OBJPROP_XDISTANCE, 15);
      ObjectSet("BG4", OBJPROP_YDISTANCE, 35);
      ObjectCreate("BG5", OBJ_LABEL, 0, 0, 0, 0, 0);
      ObjectSetText("BG5", "nnnnn", 50, "Wingdings", Black);
      ObjectSet("BG5", OBJPROP_CORNER, 0);
      ObjectSet("BG5", OBJPROP_XDISTANCE, 0);
      ObjectSet("BG5", OBJPROP_YDISTANCE, 70);
      ObjectCreate("BG6", OBJ_LABEL, 0, 0, 0, 0, 0);
      ObjectSetText("BG6", "nnnn", 50, "Wingdings", Black);
      ObjectSet("BG6", OBJPROP_CORNER, 0);
      ObjectSet("BG6", OBJPROP_XDISTANCE, 15);
      ObjectSet("BG6", OBJPROP_YDISTANCE, 70);
      ObjectCreate("BG7", OBJ_LABEL, 0, 0, 0, 0, 0);
      ObjectSetText("BG7", "nnnnn", 50, "Wingdings", Black);
      ObjectSet("BG7", OBJPROP_CORNER, 0);
      ObjectSet("BG7", OBJPROP_XDISTANCE, 0);
      ObjectSet("BG7", OBJPROP_YDISTANCE, 105);
      ObjectCreate("BG8", OBJ_LABEL, 0, 0, 0, 0, 0);
      ObjectSetText("BG8", "nnnn", 50, "Wingdings", Black);
      ObjectSet("BG8", OBJPROP_CORNER, 0);
      ObjectSet("BG8", OBJPROP_XDISTANCE, 15);
      ObjectSet("BG8", OBJPROP_YDISTANCE, 105);
      ObjectCreate("BG9", OBJ_LABEL, 0, 0, 0, 0, 0);
      ObjectSetText("BG9", "nnnnn", 50, "Wingdings", Black);
      ObjectSet("BG9", OBJPROP_CORNER, 0);
      ObjectSet("BG9", OBJPROP_XDISTANCE, 0);
      ObjectSet("BG9", OBJPROP_YDISTANCE, 128);
      ObjectCreate("BG10", OBJ_LABEL, 0, 0, 0, 0, 0);
      ObjectSetText("BG10", "nnnn", 50, "Wingdings", Black);
      ObjectSet("BG10", OBJPROP_CORNER, 0);
      ObjectSet("BG10", OBJPROP_XDISTANCE, 15);
      ObjectSet("BG10", OBJPROP_YDISTANCE, 128);
      minute_0 = minute_536;
      hour_8 = hour_540;
      day_16 = day_544;
      month_24 = month_548;
      year_32 = year_552;
      if (minute_0 < 10.0) Ls_40 = "0" + DoubleToStr(minute_0, 0);
      else Ls_40 = DoubleToStr(minute_0, 0);
      if (hour_8 < 10.0) Ls_48 = "0" + DoubleToStr(hour_8, 0);
      else Ls_48 = DoubleToStr(hour_8, 0);
      if (day_16 < 10.0) Ls_56 = "0" + DoubleToStr(day_16, 0);
      else Ls_56 = DoubleToStr(day_16, 0);
      if (month_24 < 10.0) Ls_64 = "0" + DoubleToStr(month_24, 0);
      else Ls_64 = DoubleToStr(month_24, 0);
      dbl2str_72 = DoubleToStr(year_32, 0);
      ObjectCreate("Venom_Date", OBJ_LABEL, 0, 0, 0, 0, 0);
      ObjectSetText("Venom_Date", "DATE : " + Ls_56 + "/" + Ls_64 + "/" + dbl2str_72 + "   TIME : " + Ls_48 + ":" + Ls_40, 10, "Arial Black", White);
      ObjectSet("Venom_Date", OBJPROP_CORNER, 0);
      ObjectSet("Venom_Date", OBJPROP_XDISTANCE, 8);
      ObjectSet("Venom_Date", OBJPROP_YDISTANCE, 15);
      ObjectCreate("Venom_Pair", OBJ_LABEL, 0, 0, 0, 0, 0);
      ObjectSetText("Venom_Pair", Symbol(), 30, "Arial Black", Red);
      ObjectSet("Venom_Pair", OBJPROP_CORNER, 0);
      ObjectSet("Venom_Pair", OBJPROP_XDISTANCE, 10);
      ObjectSet("Venom_Pair", OBJPROP_YDISTANCE, 25);
      ObjectCreate("Venom_Pair1", OBJ_LABEL, 0, 0, 0, 0, 0);
      ObjectSetText("Venom_Pair1", Symbol(), 30, "Arial Black", Gold);
      ObjectSet("Venom_Pair1", OBJPROP_CORNER, 0);
      ObjectSet("Venom_Pair1", OBJPROP_XDISTANCE, 8);
      ObjectSet("Venom_Pair1", OBJPROP_YDISTANCE, 23);
      RefreshRates();
      bid_80 = MarketInfo(Symbol(), MODE_BID);
      digits_88 = MarketInfo(Symbol(), MODE_DIGITS);
      spread_96 = MarketInfo(Symbol(), MODE_SPREAD);
      dbl2str_104 = DoubleToStr(bid_80, digits_88);
      dbl2str_112 = DoubleToStr(spread_96, 0);
      ObjectCreate("Venom_Price", OBJ_LABEL, 0, 0, 0, 0, 0);
      ObjectSetText("Venom_Price", "PRICE : " + dbl2str_104 + "    SPREAD : " + dbl2str_112, 10, "Arial Black", White);
      ObjectSet("Venom_Price", OBJPROP_CORNER, 0);
      ObjectSet("Venom_Price", OBJPROP_XDISTANCE, 8);
      ObjectSet("Venom_Price", OBJPROP_YDISTANCE, 72);
      RefreshRates();
      minute_120 = TimeMinute(TimeCurrent());
      hour_124 = TimeHour(TimeCurrent());
      day_128 = TimeDay(TimeCurrent());
      ObjectCreate("Buy_Signal", OBJ_LABEL, 0, 0, 0, 0, 0);
      ObjectSetText("Buy_Signal", "BUY SIGNAL", 12, "Arial Black", Silver);
      ObjectSet("Buy_Signal", OBJPROP_CORNER, 0);
      ObjectSet("Buy_Signal", OBJPROP_XDISTANCE, 9);
      ObjectSet("Buy_Signal", OBJPROP_YDISTANCE, 97);
      ObjectCreate("Buy_Signal1", OBJ_LABEL, 0, 0, 0, 0, 0);
      ObjectSetText("Buy_Signal1", "BUY SIGNAL", 12, "Arial Black", Lime);
      ObjectSet("Buy_Signal1", OBJPROP_CORNER, 0);
      ObjectSet("Buy_Signal1", OBJPROP_XDISTANCE, 8);
      ObjectSet("Buy_Signal1", OBJPROP_YDISTANCE, 96);
      ObjectCreate("Sell_Signal", OBJ_LABEL, 0, 0, 0, 0, 0);
      ObjectSetText("Sell_Signal", "SELL SIGNAL", 12, "Arial Black", Silver);
      ObjectSet("Sell_Signal", OBJPROP_CORNER, 0);
      ObjectSet("Sell_Signal", OBJPROP_XDISTANCE, 9);
      ObjectSet("Sell_Signal", OBJPROP_YDISTANCE, 137);
      ObjectCreate("Sell_Signal1", OBJ_LABEL, 0, 0, 0, 0, 0);
      ObjectSetText("Sell_Signal1", "SELL SIGNAL", 12, "Arial Black", Red);
      ObjectSet("Sell_Signal1", OBJPROP_CORNER, 0);
      ObjectSet("Sell_Signal1", OBJPROP_XDISTANCE, 8);
      ObjectSet("Sell_Signal1", OBJPROP_YDISTANCE, 136);
      var_name_132 = "venom_signal_buy" + Symbol();
      var_name_140 = "venom_signal_sell" + Symbol();
      global_var_148 = GlobalVariableGet(var_name_132);
      global_var_152 = GlobalVariableGet(var_name_140);
      RefreshRates();
      digits_156 = MarketInfo(Symbol(), MODE_DIGITS);
      bid_164 = Bid;
      var_name_172 = "venom_b_day" + Symbol();
      var_name_180 = "venom_b_price" + Symbol();
      var_name_188 = "venom_b_hour" + Symbol();
      var_name_196 = "venom_b_minute" + Symbol();
      global_var_228 = GlobalVariableGet(var_name_172);
      global_var_232 = GlobalVariableGet(var_name_180);
      global_var_240 = GlobalVariableGet(var_name_188);
      global_var_248 = GlobalVariableGet(var_name_196);
      if (global_var_232 == 0.0 && global_var_228 != day_128 && global_var_148 == 6) {
         GlobalVariableSet(var_name_180, bid_164);
         GlobalVariableSet(var_name_188, hour_124);
         GlobalVariableSet(var_name_196, minute_120);
         GlobalVariableSet(var_name_172, day_128);
      }
      if (global_var_228 != day_128 && global_var_232 != 0.0) {
         GlobalVariableSet(var_name_180, 0);
         GlobalVariableSet(var_name_132, 0);
      }
      if (global_var_232 != 0.0) {
         dbl2str_204 = DoubleToStr(global_var_232, digits_156);
         if (global_var_240 < 10.0) Ls_212 = "0" + DoubleToStr(global_var_240, 0);
         else Ls_212 = DoubleToStr(global_var_240, 0);
         if (global_var_248 < 10.0) Ls_220 = "0" + DoubleToStr(global_var_248, 0);
         else Ls_220 = DoubleToStr(global_var_248, 0);
         ObjectCreate("Buy_Price", OBJ_LABEL, 0, 0, 0, 0, 0);
         ObjectSetText("Buy_Price", "PRICE : " + dbl2str_204, 8, "Arial Black", Lime);
         ObjectSet("Buy_Price", OBJPROP_CORNER, 0);
         ObjectSet("Buy_Price", OBJPROP_XDISTANCE, 8);
         ObjectSet("Buy_Price", OBJPROP_YDISTANCE, 118);
         ObjectCreate("Buy_Time", OBJ_LABEL, 0, 0, 0, 0, 0);
         ObjectSetText("Buy_Time", "TIME : " + Ls_212 + ":" + Ls_220, 8, "Arial Black", Lime);
         ObjectSet("Buy_Time", OBJPROP_CORNER, 0);
         ObjectSet("Buy_Time", OBJPROP_XDISTANCE, 102);
         ObjectSet("Buy_Time", OBJPROP_YDISTANCE, 118);
      } else {
         ObjectDelete("Buy_Price");
         ObjectDelete("Buy_Time");
      }
      var_name_256 = "venom_j_day" + Symbol();
      var_name_264 = "venom_j_price" + Symbol();
      var_name_272 = "venom_j_hour" + Symbol();
      var_name_280 = "venom_j_minute" + Symbol();
      global_var_312 = GlobalVariableGet(var_name_256);
      global_var_316 = GlobalVariableGet(var_name_264);
      global_var_324 = GlobalVariableGet(var_name_272);
      global_var_332 = GlobalVariableGet(var_name_280);
      if (global_var_316 == 0.0 && global_var_312 != day_128 && global_var_152 == -6) {
         GlobalVariableSet(var_name_264, bid_164);
         GlobalVariableSet(var_name_272, hour_124);
         GlobalVariableSet(var_name_280, minute_120);
         GlobalVariableSet(var_name_256, day_128);
      }
      if (global_var_312 != day_128 && global_var_316 != 0.0) {
         GlobalVariableSet(var_name_264, 0);
         GlobalVariableSet(var_name_140, 0);
      }
      if (global_var_316 != 0.0) {
         dbl2str_288 = DoubleToStr(global_var_316, digits_156);
         if (global_var_324 < 10.0) Ls_296 = "0" + DoubleToStr(global_var_324, 0);
         else Ls_296 = DoubleToStr(global_var_324, 0);
         if (global_var_332 < 10.0) Ls_304 = "0" + DoubleToStr(global_var_332, 0);
         else Ls_304 = DoubleToStr(global_var_332, 0);
         ObjectCreate("Sell_Price", OBJ_LABEL, 0, 0, 0, 0, 0);
         ObjectSetText("Sell_Price", "PRICE : " + dbl2str_288, 8, "Arial Black", Red);
         ObjectSet("Sell_Price", OBJPROP_CORNER, 0);
         ObjectSet("Sell_Price", OBJPROP_XDISTANCE, 8);
         ObjectSet("Sell_Price", OBJPROP_YDISTANCE, 158);
         ObjectCreate("Sell_Time", OBJ_LABEL, 0, 0, 0, 0, 0);
         ObjectSetText("Sell_Time", "TIME : " + Ls_296 + ":" + Ls_304, 8, "Arial Black", Red);
         ObjectSet("Sell_Time", OBJPROP_CORNER, 0);
         ObjectSet("Sell_Time", OBJPROP_XDISTANCE, 102);
         ObjectSet("Sell_Time", OBJPROP_YDISTANCE, 158);
      } else {
         ObjectDelete("Sell_Price");
         ObjectDelete("Sell_Time");
      }
      time_340 = Time[0];
      if (Period() == PERIOD_M1) Li_344 = 60;
      if (Period() == PERIOD_M5) Li_344 = 300;
      if (Period() == PERIOD_M15) Li_344 = 900;
      if (Period() == PERIOD_M30) Li_344 = 1800;
      if (Period() == PERIOD_H1) Li_344 = 3600;
      if (Period() == PERIOD_H4) Li_344 = 14400;
      if (Period() == PERIOD_D1) Li_344 = 86400;
      if (Period() == PERIOD_W1) Li_344 = 604800;
      if (Period() == PERIOD_MN1) Li_344 = 2592000;
      ima_348 = iMA(NULL, PERIOD_M15, G_period_84, 0, MODE_EMA, PRICE_CLOSE, 0);
      ima_356 = iMA(NULL, PERIOD_M15, G_period_88, 0, MODE_SMA, PRICE_CLOSE, 0);
      ima_364 = iMA(NULL, PERIOD_M30, G_period_84, 0, MODE_EMA, PRICE_CLOSE, 0);
      ima_372 = iMA(NULL, PERIOD_M30, G_period_88, 0, MODE_SMA, PRICE_CLOSE, 0);
      ima_380 = iMA(NULL, PERIOD_H1, G_period_84, 0, MODE_EMA, PRICE_CLOSE, 0);
      ima_388 = iMA(NULL, PERIOD_H1, G_period_88, 0, MODE_SMA, PRICE_CLOSE, 0);
      Ld_396 = MathMax(ima_348, ima_356);
      Ld_404 = MathMax(ima_364, ima_372);
      Ld_412 = MathMax(ima_380, ima_388);
      Ld_420 = MathMax(Ld_396, Ld_404);
      Ld_428 = MathMax(Ld_412, Ld_420);
      Ld_436 = MathMin(ima_348, ima_356);
      Ld_444 = MathMin(ima_364, ima_372);
      Ld_452 = MathMin(ima_380, ima_388);
      Ld_460 = MathMin(Ld_436, Ld_444);
      Ld_468 = MathMin(Ld_452, Ld_460);
      datetime_476 = time_340 + 1 * Li_344;
      datetime_480 = time_340 + 3 * Li_344;
      ima_484 = iMA(NULL, PERIOD_H4, G_period_84, 0, MODE_EMA, PRICE_CLOSE, 0);
      ima_492 = iMA(NULL, PERIOD_H4, G_period_88, 0, MODE_SMA, PRICE_CLOSE, 0);
      datetime_500 = time_340 + Li_344 * 4;
      datetime_504 = time_340 + 6 * Li_344;
      ima_508 = iMA(NULL, PERIOD_D1, G_period_84, 0, MODE_EMA, PRICE_CLOSE, 0);
      ima_516 = iMA(NULL, PERIOD_D1, G_period_88, 0, MODE_SMA, PRICE_CLOSE, 0);
      datetime_524 = time_340 + 7 * Li_344;
      datetime_528 = time_340 + 9 * Li_344;
      ObjectCreate("2_SR", OBJ_RECTANGLE, 0, 0, 0, 0, 0);
      ObjectSet("2_SR", OBJPROP_TIME1, datetime_476);
      ObjectSet("2_SR", OBJPROP_PRICE1, ima_380);
      ObjectSet("2_SR", OBJPROP_TIME2, datetime_480);
      ObjectSet("2_SR", OBJPROP_PRICE2, ima_388);
      ObjectSet("2_SR", OBJPROP_COLOR, DarkBlue);
      ObjectSet("2_SR", OBJPROP_BACK, TRUE);
      ObjectCreate("3_SR", OBJ_RECTANGLE, 0, 0, 0, 0, 0);
      ObjectSet("3_SR", OBJPROP_TIME1, datetime_500);
      ObjectSet("3_SR", OBJPROP_PRICE1, ima_484);
      ObjectSet("3_SR", OBJPROP_TIME2, datetime_504);
      ObjectSet("3_SR", OBJPROP_PRICE2, ima_492);
      ObjectSet("3_SR", OBJPROP_COLOR, Blue);
      ObjectSet("3_SR", OBJPROP_BACK, TRUE);
      ObjectCreate("4_SR", OBJ_RECTANGLE, 0, 0, 0, 0, 0);
      ObjectSet("4_SR", OBJPROP_TIME1, datetime_524);
      ObjectSet("4_SR", OBJPROP_PRICE1, ima_508);
      ObjectSet("4_SR", OBJPROP_TIME2, datetime_528);
      ObjectSet("4_SR", OBJPROP_PRICE2, ima_516);
      ObjectSet("4_SR", OBJPROP_COLOR, DeepSkyBlue);
      ObjectSet("4_SR", OBJPROP_BACK, TRUE);
   }
   return (0);
}